version: "3"

services:
  web:
    build: .
    command: npm run dev
    restart: always
    links: 
      - postgres
    depends_on: 
      - postgres
      - mongo
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3100:3100"
  
  postgres:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    expose:
      - 5432
    environment: 
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "dnedb"
    volumes:
      - ~/dbdata:/var/lib/postgresql/data

  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    expose:
      - 27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_DATABASE: "dnedb"
    
  adminer:
    image: adminer
    restart: always
    ports: 
      - "8080:8080"
    depends_on: 
      - postgres
    expose: 
      - 8080

  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo

    #docker exec -it dne-node-api_mongo_1 mongo --host localhost -u root -p root --authenticationDatabase admin --eval "db.getSiblingDB('dnedb').createUser({user: 'root', pwd: 'root', roles: [{role: 'readWrite', db: 'dnedb'}]})"

    #consigo rodar um docker exec no docker-compose ?
    #consigo rodar um RUN dentro de um docker-compose